### ISSUE TITLE
powerline renders endlessly. 

### ISSUE THREAD

**Issue by fullstopslash** [powerline/powerline#1749] opened 2017-04-09 15:16 UTC
It goes once per second until it floods the screen. 
![2017-04-09-111051_1920x1080_scrot](https://cloud.githubusercontent.com/assets/299944/24838433/b782226a-1d15-11e7-9ad5-7ebc2af6ca11.png)

**Comment by ZyX-I** [comment] 2017-04-09 15:20
Looks like a duplicate of https://github.com/powerline/powerline/issues/1652. In any case this is not a powerline bug: it is tmux which displays status lines, powerline only tells it what to display.

**Closed by ZyX-I** 2017-04-09 15:20 UTC
