### ISSUE TITLE
Design issue in Ubuntu 16.04

### ISSUE THREAD

**Issue by banerjeesamrat** [powerline/powerline#1846] opened 2017-10-12 06:36 UTC
My colleague had installed Powerline few days back in his Linux  Elementary OS and I really liked the way it was designed and went ahead too but I am facing a minor issue in changing the appearance of the directory name appearing in the terminal window

![image](https://user-images.githubusercontent.com/31121849/31482268-289bcd14-af17-11e7-90cc-626bf5171c18.png)

While I needed this above look but what I am getting is this:

![image](https://user-images.githubusercontent.com/31121849/31482315-5694b9b0-af17-11e7-8b1c-08b6cd37c7e6.png)

I need some guidance on how to make it look like the above image

**Comment by ZyX-I** [comment] 2017-10-12 07:01
This is duplicate of #1842 (and a bunch of others as well).

**Closed by ZyX-I** 2017-10-12 07:01 UTC
Labels: c:b:shell, s:duplicate, s:invalid:error in environment, t:bug

**Comment by banerjeesamrat** [comment] 2017-10-12 14:18
You closed it surely and deleted my comment but it still doesen't work

![image](https://user-images.githubusercontent.com/31121849/31500855-243a17ee-af58-11e7-999b-375321ff172c.png)

**Comment by ZyX-I** [comment] 2017-10-12 20:59
I did not delete any comments.

**Comment by banerjeesamrat** [comment] 2017-10-13 05:21
@ZyX-I atleast help me with the solution for the above problem

**Comment by ZyX-I** [comment] 2017-10-13 06:08
@banerjeesamrat You did see my reply in the other issue, did not you?
