### ISSUE TITLE
Tmux powerline eating up screen on Arch linux

### ISSUE THREAD

**Issue by aiguofer** [powerline/powerline#1678] opened 2016-11-08 03:00 UTC
Hi, I'm not entirely sure when this started happening but my tmux powerline setup is eating up my screen on my Arch install. Every few seconds the status line eats another line.

Interestingly enough, this only happens when I'm logged in through my DE (Using Gnome 3.22, it happens if I use Classic, Xorg, or Wayland). If I ssh in and attach to the tmux session, everything seems good. I'm thinking the problem might lie elsewhere, but thought I'd start here.

Using:
powerline 2.5-1
tmux 2.3-1

![tmux](https://cloud.githubusercontent.com/assets/780934/20085264/9899cc16-a535-11e6-9a1e-22bdf747ee35.gif)

**Comment by ZyX-I** [comment] 2016-11-08 19:44
Duplicate of #1652

**Closed by ZyX-I** 2016-11-08 19:44 UTC
Labels: c:b:tmux, s:duplicate, t:bug
