### ISSUE TITLE
Powerline with Tmux are "ignoring" (?) left side.

### ISSUE THREAD

**Issue by Siprah** [powerline/powerline#1592] opened 2016-05-09 20:50 UTC
I have a weird problem with using Powerline with Tmux. It just ignoring my changes for left side of panel, right side works correctly. 

Screenshot: ![http://puu.sh/oM2oZ/39f447dd37.png](http://puu.sh/oM2oZ/39f447dd37.png)

My .tmux.conf file looks that:

```
set -g default-terminal "screen-256color"
run-shell "powerline-daemon -q"

# change shell to zsh
set-option -g default-shell /bin/zsh

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# use hjkl for moving
# and HJKL for resizing
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# don't rename windows automatically
set-option -g allow-rename off

######################
### DESIGN CHANGES ###
######################

source "/usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"
```

I'm using OS X, tmux version is 2.1. What am I doing wrong?

**Comment by ZyX-I** [comment] 2016-05-09 21:24
If I am not mistaking this is duplicate of #1583.

**Closed by ZyX-I** 2016-05-09 21:24 UTC
Labels: c:b:tmux, s:duplicate, t:bug
