### ISSUE TITLE
Python warning at startup

### ISSUE THREAD

**Issue by binarykitchen** [powerline/powerline#1587] opened 2016-05-04 22:07 UTC
I see this every time

```
~ ❯❯❯ vi
You need vim compiled with Python 2.6, 2.7 or 3.2 and later support
for Powerline to work. Please consult the documentation for more
details.
Press ENTER or type command to continue
```

Any ideas why? It didn't happen before I upgraded Ubuntu to 15.04 ...

**Comment by ZyX-I** [comment] 2016-05-04 22:09
You have this warning because your Vim is compiled without Python support. This is exactly what warning tells you. I cannot say why you got such Vim, but in any case this is duplicate of #1584 and this is not a powerline issue.

**Closed by ZyX-I** 2016-05-04 22:09 UTC
Labels: c:b:vim, s:duplicate, s:invalid:unsupported software, t:bug
