### ISSUE TITLE
vim: Selecting tabs with mouse cycles tab instead of select

### ISSUE THREAD

**Issue by erikw** [powerline/powerline#1696] opened 2016-12-16 14:10 UTC
If vim is configured with `set mouse=a` you can click on the tabs to select a tab. If powerline is enabled in vim, then a click on any tab will instead cycle to the next tab, like `gt` in normal mode, instead of selecting the clicked tab.

**System:**
Powerline: `2.5`, python3 version, installed with pip3.
Vim: `8.0`
Python: `3.5.2`
Terminal emulator: iTerm `3.012`
OS: macOS Sierra 10.12.1

Very annoying :-)

**Comment by ZyX-I** [comment] 2016-12-16 14:56
Duplicate of https://github.com/powerline/powerline/issues/1353.

**Comment by erikw** [comment] 2016-12-16 15:00
@ZyX-I that issue is closed though, can you reopen it?

**Comment by ZyX-I** [comment] 2016-12-16 15:02
@erikw Relevant patches are already merged and should work. Are you using default configuration or have copied it somewhere at some older version?

**Comment by ZyX-I** [comment] 2016-12-16 15:05
It was merged in powerline-2.2.

**Comment by erikw** [comment] 2016-12-16 15:18
Ahh it was outdated config files. Now it works. Thanks :)

**Closed** 2016-12-16 15:22 UTC
Labels: c:b:vim, s:invalid:configuration error, t:bug
