### ISSUE TITLE
IPython (>=5.0.0) bindings needs to be updated

### ISSUE THREAD

**Issue by jadelord** [powerline/powerline#1627] opened 2016-07-27 12:32 UTC
Loading powerline extension as described in the documentation for IPython results in the following error:

```python
$ ipython2
Python 2.7.12 (default, Jun 28 2016, 08:31:05) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
[TerminalIPythonApp] WARNING | Error in loading extension: powerline.bindings.ipython.post_0_11
Check your config files in /home/avmo/.ipython/profile_default
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/IPython/core/shellapp.py", line 246, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/usr/lib/python2.7/site-packages/IPython/core/extensions.py", line 83, in load_extension
    __import__(module_str)
  File "/usr/lib/python2.7/site-packages/powerline/bindings/ipython/post_0_11.py", line 6, in <module>
    from IPython.core.prompts import PromptManager
ImportError: cannot import name PromptManager

In [1]:                           
```

## How to replicate
* Use ipython==5.0.0 and powerline 2.4
* Follow instructions in http://powerline.readthedocs.io/en/master/usage/other.html#ipython-prompt
* Launch ipython.

## Reason

See https://raw.githubusercontent.com/ipython/ipython/000f321c8bed714d2fc776ef83b845b116610e87/docs/source/whatsnew/version5.rst

> The ``PromptManager`` class has been removed, and the prompt machinery simplified.
See `custom_prompts` to customise prompts with the new machinery.

**Comment by ZyX-I** [comment] 2016-07-27 12:44
2.4 is outdated.

**Comment by ZyX-I** [comment] 2016-07-27 12:45
Duplicate of #1617

**Closed by ZyX-I** 2016-07-27 12:44 UTC
