### ISSUE TITLE
Where are the fonts?

### ISSUE THREAD

**Issue by davidbarratt** [powerline/powerline#1346] opened 2015-04-10 17:22 UTC
In the docs
https://github.com/powerline/powerline/blob/develop/docs/source/installation/osx.rst#fonts-installation
it says "Install downloaded patched font by double-clicking the font file in Finder"

What folder would this be in?

**Comment by ZyX-I** [comment] 2015-04-10 18:30
Link to the repository is in https://powerline.readthedocs.org/en/latest/installation.html#fonts-installation. I would also highly suggest not to use github for viewing documentation: it is not using sphinx to compile it and some files are missing critical pieces.

**Comment by ZyX-I** [comment] 2015-05-10 14:34
It is downloaded. It will be in whatever folder you downloaded it. Marking as `s:not a bug` because I do not want to repeat information from top-level installation documentation.

**Closed by ZyX-I** 2015-05-10 14:34 UTC
Labels: c:documentation, s:not a bug, t:bug
