### ISSUE TITLE
powerline-config crash

### ISSUE THREAD

**Issue by jwhitley** [powerline/powerline#1273] opened 2015-01-14 19:05 UTC
`powerline-config tmux setenv` on current `develop` (761a035765bdc16a634b4052cc85000798310f61) crashes with backtrace:

```
# powerline-config tmux setenv

Traceback (most recent call last):
  File "/usr/local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/usr/local/lib/python2.7/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/powerline/bindings/config.py", line 93, in init_environment
    powerline = ShellPowerline(finish_args(EmptyArgs('tmux', args.config_path)))
TypeError: finish_args() takes exactly 2 arguments (1 given)
```

Commit 917dfed84240078da8dab1edc380df63dbd243cd appears to be the culprit, as it added an argument to `finish_args()` (in powerline.commands.main), but missed (at least) the invocation at [powerline/bindings/config.py:93](https://github.com/powerline/powerline/blob/c9d1b81954f63366489528b3511bc87444b9760d/powerline/bindings/config.py#L93).

/cc @ZyX-I

**Comment by jwhitley** [comment] 2015-01-14 19:59
I rolled back a bit and found that `powerline-config tmux setenv` fails with a different error:

```
# powerline-config tmux setenv

Traceback (most recent call last):
  File "/usr/local/bin/powerline-config", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/whitley/src/3p/powerline/scripts/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/Users/whitley/src/3p/powerline/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/Users/whitley/src/3p/powerline/powerline/bindings/config.py", line 139, in init_environment
    attrs = attr_to_tmux_attr(get_highlighting(group)[attr])
NameError: global name 'attr_to_tmux_attr' is not defined
```

After that, I fired up git bisect and it appears that the above command doesn't work on or after commit c868f9c2559f8eb95c99359867cb4e0bbb5ea66f.

That commit has log message "Rename `attr` to `attrs`", and looking it over, the exception seems to be a pretty straightforward missed identifier from that renaming.  Between this error and the one above, it looks like there's a code path here that's not covered by the unit tests?

**Comment by ZyX-I** [comment] 2015-01-14 20:05
Duplicate of #1264.

**Closed by ZyX-I** 2015-01-14 20:05 UTC
Labels: bug, duplicate, tmux
