### ISSUE TITLE
Missing color on tmux windows?

### ISSUE THREAD

**Issue by thegcat** [powerline/powerline#1264] opened 2015-01-10 13:28 UTC
![bildschirmfoto 2015-01-10 um 14 23 58](https://cloud.githubusercontent.com/assets/22835/5691713/94f34192-98d4-11e4-8e38-9b65f541177b.png)

I have updated powerline from way back when, redid my whole config to be sure (basically I just removed segments from the right side), but I'm missing colors in the left side.

How can I check if powerline is indeed sending the color information correctly and I should be looking later down the line, or if I should be looking at powerline? Thanks.

**Comment by ZyX-I** [comment] 2015-01-10 16:27
The very first thing you should try is running `powerline-lint` and fixing all of the errors it shows. Currently I am preparing for the 2.0 release and have pushed a bunch of incompatible changes that make old configuration invalid (though to fix it you only need to do some renamings: structure and semantics neither did change nor was extended).

After doing this make sure that `powerline-config tmux setenv && powerline-config tmux source` does not show any errors. Then check out daemon output (if you are using one) (run with `powerline-daemon --replace --foreground` to replace currently running instance and see its output in terminal) and run `powerline tmux right`.

**Comment by jwegne** [comment] 2015-01-10 20:35
Hi,
I have the same issues. Here are the infos you are requested:
- `powerline-lint` reports no error
- `powerline-config tmux setenv` throws following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/powerline-config", line 8, in <module>
    execfile(__file__)
  File "/Users/jwegne/Projects/git/powerline/scripts/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/Users/jwegne/Projects/git/powerline/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/Users/jwegne/Projects/git/powerline/powerline/bindings/config.py", line 93, in init_environment
    powerline = ShellPowerline(finish_args(EmptyArgs('tmux', args.config_path)))
TypeError: finish_args() takes exactly 2 arguments (1 given)
```
- `powerline-config tmux source` returns
```
set option: status -> on
set option: status-utf8 -> on
set option: status-interval -> 2
set option: status-left-length -> 20
set option: status-right -> "#(env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"`)"
set option: status-right-length -> 150
set option: window-status-format -> "#[]#I #[]#[default]#W "
set option: window-status-current-format -> "#[]#[]#I #[]#W #[]"
set option: status-left -> "#[] #S #[]#(eval $POWERLINE_COMMAND tmux left)"
```
- `powerline tmux right` returns
```
#[fg=colour8,bg=default,nobold,noitalics,nounderscore] #[fg=colour14,bg=colour8,nobold,noitalics,nounderscore] ⇑  5d 10m 54s#[fg=colour0,bg=colour8,nobold,noitalics,nounderscore] #[fg=colour2,bg=colour0,nobold,noitalics,nounderscore] 2.2 #[fg=colour2,bg=colour0,nobold,noitalics,nounderscore]1.9 #[fg=colour2,bg=colour0,nobold,noitalics,nounderscore]1.9#[fg=colour11,bg=colour0,nobold,noitalics,nounderscore] #[fg=colour15,bg=colour11,nobold,noitalics,nounderscore] 2015-01-10#[fg=colour7,bg=colour11,nobold,noitalics,nounderscore] #[fg=colour7,bg=colour11,nobold,noitalics,nounderscore] ⌚ 21:33#[fg=colour14,bg=colour11,nobold,noitalics,nounderscore] #[fg=colour15,bg=colour14,nobold,noitalics,nounderscore]  4DELJWEGNE.local % 
```
- No `powerline-daemon --foreground` output

**Comment by thegcat** [comment] 2015-01-10 21:15
* `powerline-lint` no output
* `powerline-config tmux setenv`
```
Traceback (most recent call last):
  File "/usr/local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/usr/local/lib/python2.7/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/powerline/bindings/config.py", line 93, in init_environment
    powerline = ShellPowerline(finish_args(EmptyArgs('tmux', args.config_path)))
TypeError: finish_args() takes exactly 2 arguments (1 given)
```
* `powerline-config tmux source`
```
set option: status -> on
set option: status-utf8 -> on
set option: status-interval -> 2
set option: status-left-length -> 20
set option: status-right -> "#(env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"`)"
set option: status-right-length -> 150
set option: window-status-format -> "#[]#I #[]#[default]#W "
set option: window-status-current-format -> "#[]#[]#I #[]#W #[]"
set option: status-left -> "#[] #S #[]#(eval $POWERLINE_COMMAND tmux left)"
```
* `powerline-daemon --replace --foreground`
```
Kill command sent to daemon, waiting for daemon to exit, press Ctrl-C to terminate wait and exit
```
And nothing more seems to happen until I exit it.
* `powerline tmux right`
```
#[fg=colour252,bg=default,nobold,noitalics,nounderscore] #[fg=colour16,bg=colour252,bold,noitalics,nounderscore]  localhost 
```

I'm missing the colours on the right where the tmux pane titles are though.

**Comment by thegcat** [comment] 2015-01-10 21:15
And thanks for your quick help!

**Comment by thegcat** [comment] 2015-01-10 21:17
(note: I first wrote "I'm missing the colours on the right where the tmux pane titles are though." at the end of my comment before the last, I meant the colours on the _left_ where the tmux pane titles are, sorry for the confusion)

**Comment by ZyX-I** [comment] 2015-01-10 21:20
@thegcat Referenced commit should fix the issue. But I definitely need functional tests for tmux.

**Comment by thegcat** [comment] 2015-01-10 21:30
@ZyX-I It gets me to a different error :-/

```
powerline-config tmux setenv
2015-01-10 22:28:48,908:ERROR:t:powerline:Failed to create renderer: u't'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/powerline/__init__.py", line 742, in update_renderer
    self.create_renderer(**cr_kwargs)
  File "/usr/local/lib/python2.7/site-packages/powerline/__init__.py", line 507, in create_renderer
    self.ext_config = config['ext'][self.ext]
KeyError: u't'
2015-01-10 22:28:48,908:ERROR:t:powerline:Failed to create renderer: u't'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/powerline/__init__.py", line 742, in update_renderer
    self.create_renderer(**cr_kwargs)
  File "/usr/local/lib/python2.7/site-packages/powerline/__init__.py", line 507, in create_renderer
    self.ext_config = config['ext'][self.ext]
KeyError: u't'
Traceback (most recent call last):
  File "/usr/local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/usr/local/lib/python2.7/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/powerline/bindings/config.py", line 96, in init_environment
    powerline.update_renderer()
  File "/usr/local/lib/python2.7/site-packages/powerline/__init__.py", line 742, in update_renderer
    self.create_renderer(**cr_kwargs)
  File "/usr/local/lib/python2.7/site-packages/powerline/__init__.py", line 507, in create_renderer
    self.ext_config = config['ext'][self.ext]
KeyError: u't'
```

**Comment by ZyX-I** [comment] 2015-01-11 00:07
Everything should be fixed now in #1265 and I have a functional test.

**Comment by thegcat** [comment] 2015-01-11 08:13
![bildschirmfoto 2015-01-11 um 09 12 10](https://cloud.githubusercontent.com/assets/22835/5694658/03c3f13c-9972-11e4-86b4-287198aa278e.png)

Works a charm now, thanks a lot!

Would you want the output from the above commands again for reference?

**Comment by phinze** [comment] 2015-01-11 16:37
Just ran into this same issue, confirmed that reinstalling powerline from second fix commit solves it:

```
pip install -U git+git://github.com/ZyX-I/powerline@4abeab04bd36c07f8695195b7c789069ac5a5188
```

**Comment by djbender** [comment] 2015-01-12 01:25
@phinze: +1 worked for me too.

**Comment by jwegne** [comment] 2015-01-12 06:30
Thank you very much, the patch also works for me.

**Closed** 2015-01-16 21:55 UTC
Labels: bug, tmux
