### ISSUE TITLE
Json error with i3bar binding 

### ISSUE THREAD

**Issue by Ulfr26** [powerline/powerline#1875] opened 2018-01-22 00:24 UTC
So I was trying to install powerline on my i3bar, as it seemed to work perfectly on bash and would make the bar look a lot nicer with my i3 config. The problem is that everytime I run it the bar only displays `Error: Could not parse JSON (parse error: after array element, I expect ',' or ']').

**Comment by ZyX-I** [comment] 2018-01-22 00:38
Which i3 and powerline versions? I am currently using powerline with 4.13 and I remember that I needed to create some fixes to be able to do so. But it was supposed to work without those fixes some time in the past, before I started to use i3 so something clearly changed.

Ah, and it looks like those fixes are not in any release yet; according to log 1e6414d0 was created right after (in history DAG) 2.6 release.

**Comment by Ulfr26** [comment] 2018-01-22 00:52
I'm using i3bar verion 4.14.1 and powerline 2.6, so in that case I'll try installing the development version.

**Comment by Ulfr26** [comment] 2018-01-22 01:10
I'm getting a different error now, the script isn't even running. bindings/wm/__init__.py calls [i3 Communication].Subscription(callbac, event) when the Communication object doesn't have a method named 'Subscription.' Is this a problem with my i3ipc version?

**Comment by ZyX-I** [comment] 2018-01-22 08:18
Not sure, never got this error.

**Comment by ZyX-I** [comment] 2018-01-22 08:20
I have i3ipc version 1.3.0 and pip says it is the latest one.

**Comment by s-ol** [comment] 2018-01-22 11:28
just confirming that the bindings *were* working back when I wrote and used them, I think this was around i3 4.1.3. I have since moved to powerline + lemonbar because i3bar used to not support background colors (I think this might have changed now?).

@Ulfr26 try comparing your binding with the lemonbar one, that one works for sure (specifically regarding the i3ipc handling).

**Comment by ZyX-I** [comment] 2018-01-22 20:22
@s-ol Do not remember what version was when I started using i3, but they certainly stopped to. And yes, i3bar now does support background color without needing to apply external patches.

**Comment by Ulfr26** [comment] 2018-01-24 01:33
@s-ol I'll try lemonbar when I can and tell you how it goes

**Comment by Aurze** [comment] 2018-05-30 03:26
I've run into the same bug. Turn out it happen if you have i3-py and i3ipc. I fixed a import check. The fix is in this pull request @https://github.com/powerline/powerline/pull/1914

**Comment by huiyiqun** [comment] 2018-07-07 17:43
This problem is caused by unexpected exceptions of `powerline-i3.py`.

I'm confused why should exceptions of powerline-i3 be printed to `stdout`?

**Comment by huiyiqun** [comment] 2018-07-07 18:14
I guess it has been fixed by https://github.com/powerline/powerline/commit/1e6414d0e8c85b44c91698263d74804349abb980#diff-772dbf7d219a6c05bc14c3f4f4b64461R21

**Closed** 2019-02-12 05:10 UTC
Labels: c:e:wm, t:bug
