### ISSUE TITLE
tmux duplicates statusline on every refresh of the powerline status

### ISSUE THREAD

**Issue by Kaegell** [powerline/powerline#1671] opened 2016-10-29 11:42 UTC
Hello,
I have tried to use powerline with tmux but, for some reasons, tmux is duplicating the statusline on every time the data of one of the right segments is modified (for example, the CPU load, the time or the uptime)

I am currently using MATE Terminal, but I have also been able to replacate this bug on other term emulators: urxvt, xterm, termite and Tilda.
![screenshot at 2016-10-29 13-33-20](https://cloud.githubusercontent.com/assets/7113941/19829293/e7a6d6e2-9ddc-11e6-9839-3e1532ac250c.png)
*The bug on MATE Terminal*

I am pretty sure powerline is at cause here, I have try to modify the POWERLINE_COMMAND variable, and the problem stopped. I have also managed to stop the duplication by setting the value of my right segment to something else (for instance : `set status-right 1`).

Another thing I managed to spot is that sometimes, when I start pwerline for tmux, an odd string appears in my left segment. It happens rather fast, so I've not been able to take a screencap, but it was something like "<env $POWERLI"

EDIT : just after finishing writing this report, I actually managed to take a screenshot of the string : 
![screenshot at 2016-10-29 13-43-22](https://cloud.githubusercontent.com/assets/7113941/19829338/f785f83a-9ddd-11e6-80e0-465d52964f96.png)

**Comment by ZyX-I** [comment] 2016-10-29 12:20
Duplicate of #1652. Also see #1502.

**Closed by ZyX-I** 2016-10-29 12:20 UTC
Labels: c:b:tmux, s:duplicate, t:bug
