### ISSUE TITLE
`powerline-config tmux setup` fails when using tmux compiled from github master since tmux commit c034670

### ISSUE THREAD

**Issue by agrajag9** [powerline/powerline#1734] opened 2017-03-06 23:04 UTC
In commit c034670 to the tmux repo, `powerline-config tmux setup` has returned the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/usr/local/lib/python2.7/dist-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/powerline/bindings/config.py", line 181, in tmux_setup
    tmux_version = get_tmux_version(pl)
  File "/usr/local/lib/python2.7/dist-packages/powerline/bindings/tmux/__init__.py", line 79, in get_tmux_version
    major, minor = version_string.split('.')
ValueError: need more than 1 value to unpack
```

This is due to tmux author @nicm removing the version number from `configure.ac` so that `tmux -V` now returns `tmux master` instead of `tmux 2.4`.

> programs should not rely on the format of tmux -V

For reference: 

[https://github.com/tmux/tmux/commit/c0346701dfa2a4aa4c2ea6f05157406bcfb7a50b](https://github.com/tmux/tmux/commit/c0346701dfa2a4aa4c2ea6f05157406bcfb7a50b)

[https://github.com/tmux/tmux/issues/810](https://github.com/tmux/tmux/issues/810)

**Comment by StevenWard94** [comment] 2017-03-18 05:10
I am also experiencing this exact issue. When running `powerline-config tmux setup` I receive an identical error message, except that I have powerline installed in `~/.local/lib` so, naturally, my file paths are a little different, but otherwise the output is the same and the command returns a value of '1'.

**Comment by s-ol** [comment] 2017-03-18 15:23
duplicate of #1727

**Closed** 2017-05-20 21:57 UTC
Labels: c:b:tmux, t:bug
