### ISSUE TITLE
VCS Branch Segment Doesn't Display in Tmux

### ISSUE THREAD

**Issue by rfkrocktk** [powerline/powerline#1619] opened 2016-07-13 21:11 UTC
`$HOME/.config/powerline/themes/tmux/default.json`:

```
{
    "segments": {
        "right": [
            {
                "function": "powerline.segments.common.time.date"
            },
            {
                "function": "powerline.segments.common.vcs.branch"
            },
            {
                "function": "powerline.segments.common.time.date",
                "name": "time",
                "args": {
                    "format": "%H:%M",
                    "istime": true
                }
            },
            {
                "function": "powerline.segments.common.net.hostname"
            }
        ]
    }
}
````

Screenshot:

![screenshot from 2016-07-13 14 10 44](https://cloud.githubusercontent.com/assets/347571/16819956/9bd05a0a-4903-11e6-9ade-cdb089632905.png)

The `git` binary is on my path, and all other segments display. Is there a way to debug _why_ the segment isn't being shown? I'm running the latest powerline release.

**Comment by ZyX-I** [comment] 2016-07-13 21:16
Duplicate of #1535.

**Closed by ZyX-I** 2016-07-13 21:16 UTC
Labels: c:b:tmux, c:VCS support, s:duplicate
