### ISSUE TITLE
No fancy colors in vim with Mint 19

### ISSUE THREAD

**Issue by eblis** [powerline/powerline#1927] opened 2018-07-06 09:44 UTC
I've recently updated to Mint 19 and seem to have lost powerline fancy colors in vim (but they work in the other locations I was using them, zsh and tmux).
Is there any way to get the colors back ?

![image](https://user-images.githubusercontent.com/540188/42371730-0521830e-8119-11e8-824a-6a7829082412.png)

The colors are fine in tmux though, as you can see (although vim's colors are slightly different, but that's probably a vim issue)
![image](https://user-images.githubusercontent.com/540188/42371901-7799e80e-8119-11e8-9ea4-4540d721faa4.png)

**Comment by farid-fari** [comment] 2018-09-21 16:50
I am still getting this bug, running within tmux and zsh. None of the solutions work.

They do however work on vim sessions run outside of tmux.

**Comment by lmoellendorf** [comment] 2020-03-19 23:26
> I am still getting this bug, running within tmux and zsh. None of the solutions work.
> 
> They do however work on vim sessions run outside of tmux.

I have the same issue. No colors in vim as reported by eblis, none of the solutions suggested by ZyX-I work and as farid-fari reports, colors in vim work if vim is run outside of tmux.

Any suggestions how to track this down?

**Comment by farid-fari** [comment] 2020-03-19 23:29
I no longer have this issue. I believe what has solved it for me is setting `$TERM` to `tmux-256color` but I am unsure since I cannot reproduce.

**Comment by lmoellendorf** [comment] 2020-03-19 23:37
Yes, my `TERM` in tmux was set to `screen`. Setting it to `alacritty` as outside of tmux worked. But you are right, `tmux-256color` is the better choice within tmux.

Thank you for the quick reply, @farid-fari!

**Comment by BlitzKraft** [comment] 2020-08-16 00:48
Marking it as closed. `tmux-256color` should solve this.

**Closed by BlitzKraft** 2020-08-16 00:48 UTC
Labels: c:e:vim, t:bug
