### ISSUE TITLE
tmux left side segments are being overwritten by everything else

### ISSUE THREAD

**Issue by BlitzKraft** [powerline/powerline#1583] opened 2016-04-25 15:00 UTC
I have only one segment(IP address) on the left side of tmux. When I either start powerline or source tmux.conf, I see the segment show up momentarily, only to be overdrawn by the rest of the segments. 

![2016-04-25-094225_1918x157_scrot](https://cloud.githubusercontent.com/assets/6516167/14787683/12869d12-0aca-11e6-8b20-664cac5df089.png)

However, if I move the segment to the right, it shows up.
![2016-04-25-094630_1919x139_scrot](https://cloud.githubusercontent.com/assets/6516167/14787790/af726994-0aca-11e6-84dd-e7c2b1dd9faa.png)

The only difference is where I put the IP address segment.

The output for `powerline tmux left`

```
#[fg=colour247,bg=colour233,nobold,noitalics,nounderscore] 71.14.228.130 #[fg=colour233,bg=default,nobold,noitalics,nounderscore] 
```

For `powerline tmux right`

```
#[fg=colour160,bg=default,nobold,noitalics,nounderscore] #
[fg=colour231,bg=colour160,bold,noitalics,nounderscore] ✉ 2#
[fg=colour231,bg=colour160,nobold,noitalics,nounderscore] #
[fg=colour231,bg=colour160,bold,noitalics,nounderscore] ✉ 1#
[fg=colour236,bg=colour160,nobold,noitalics,nounderscore] #
[fg=colour252,bg=colour236,bold,noitalics,nounderscore] ⌚ 09:49#
[fg=colour233,bg=colour236,nobold,noitalics,nounderscore] #
[fg=colour231,bg=colour233,nobold,noitalics,nounderscore]  #
[fg=colour1,bg=colour233,nobold,noitalics,nounderscore]♥♥♥♥♥#
[fg=colour231,bg=colour233,nobold,noitalics,nounderscore]#
[fg=colour252,bg=colour233,nobold,noitalics,nounderscore] #
[fg=colour16,bg=colour252,bold,noitalics,nounderscore]  BlitzKomp
```
(newlines added by me for clarity, but were not present in the output)

My default theme (`themes/tmux/default.json`) : http://pastebin.com/CyGgeGGS
My tmux.conf : http://pastebin.com/jxgY3NiU

**Comment by ZyX-I** [comment] 2016-04-25 15:03
@BlitzKraft Congrulations, you need to change your email passwords.

**Comment by BlitzKraft** [comment] 2016-04-25 15:06
Well. Shit.

Done. That was a really stupid mistake. Thank you for the response.

**Comment by ZyX-I** [comment] 2016-04-25 15:06
Tmux version?

**Comment by BlitzKraft** [comment] 2016-04-25 15:08
2.1

**Comment by ZyX-I** [comment] 2016-04-25 15:25
This looks like some kind of regression. Powerline code works in 2.0. More like some status option was merged with some other.

**Comment by ZyX-I** [comment] 2016-04-25 15:28
No, I am wrong. More looks like it stopped to use part of the `status-left` option for some reason.

**Comment by BlitzKraft** [comment] 2016-04-25 15:29
I tried using `set set-status-left #(powerline tmux left)` and without, in tmux.conf. Didn't make any difference.

**Comment by ZyX-I** [comment] 2016-04-25 15:32
This has something to do with escaping.

**Comment by ZyX-I** [comment] 2016-04-25 15:36
It looks like tmux added special rules for parsing options, specifically writing `\$VAR` inside `#()` results in literal `\$VAR` sent to shell (previously: sent `$VAR`).

**Comment by ZyX-I** [comment] 2016-04-25 15:37
This patch should fix the issue:

```Patch
diff --git a/powerline/bindings/tmux/powerline_tmux_2.1_plus.conf b/powerline/bindings/tmux/powerline_tmux_2.1_plus.conf
new file mode 100644
index 0000000..6ee5c8b
--- /dev/null
+++ b/powerline/bindings/tmux/powerline_tmux_2.1_plus.conf
@@ -0,0 +1,2 @@
+# Starting from tmux-2.1 escaping of dollar signs inside #() is harmful
+set -qg status-left "#{?client_prefix,#[fg=$_POWERLINE_SESSION_PREFIX_FG]#[bg=$_POWERLINE_SESSION_PREFIX_BG]#[$_POWERLINE_SESSION_PREFIX_ATTR],#[fg=$_POWERLINE_SESSION_FG]#[bg=$_POWERLINE_SESSION_BG]#[$_POWERLINE_SESSION_ATTR]} #S #{?client_prefix,#[fg=$_POWERLINE_SESSION_PREFIX_BG],#[fg=$_POWERLINE_SESSION_BG]}#[bg=$_POWERLINE_BACKGROUND_BG]#[nobold]$_POWERLINE_LEFT_HARD_DIVIDER#(env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left --width=`tmux display -p '#{client_width}'` -R width_adjust=`tmux show-options -g status-right-length | cut -d' ' -f2` -R pane_id=\"`tmux display -p '#D'`\")"
```

**Comment by BlitzKraft** [comment] 2016-04-25 15:57
Yes! It worked.

**Comment by zackp30** [comment] 2016-04-30 10:13
I've been having this issue for a while now, the patch fixed it! Thanks!

**Closed** 2016-04-30 19:48 UTC
Labels: c:b:tmux, t:bug
