### ISSUE TITLE
Tmux 2.2 with Powerline 2.5 repeats the statusline with every update

### ISSUE THREAD

**Issue by anassahmed** [powerline/powerline#1661] opened 2016-10-22 04:56 UTC
I've recently updated my system (Fedora 25) which comes with tmux 2.2 and I noticed strange effect; every time powerline updates the uptime in the statusline, it repeats the whole line in a new line again as seen in the following image:

![screenshot from 2016-10-22 06-44-15](https://cloud.githubusercontent.com/assets/928614/19616986/3082be3c-982c-11e6-90be-557f1e242478.png)

I've used `powerline` and `tmux-powerline` packages from official fedora repos (their versions are 2.5), in addition to cloning the git repository and using the last stable `master` branch with tag `2.5`. Both give the same issue.

I've also tried to comment all my options in `~/.tmux.conf` except the powrline loading part, but no avail.

My `~/.tmux.conf`:
```tmux
# force reload ~/.tmux.conf using PREFIX r
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# act like GNU screen
unbind C-b
set -g prefix C-a

# quick pane cycling
unbind ^A
bind ^A select-pane -t :.+

# # smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"

# act like vim
setw -g mode-keys vi
# bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)g?(view|vim?)(diff)?$' && tmux send-keys C-h) || tmux select-pane -L"
# bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)g?(view|vim?)(diff)?$' && tmux send-keys C-j) || tmux select-pane -D"
# bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)g?(view|vim?)(diff)?$' && tmux send-keys C-k) || tmux select-pane -U"
# bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)g?(view|vim?)(diff)?$' && tmux send-keys C-l) || tmux select-pane -R"
# bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)g?(view|vim?)(diff)?$' && tmux send-keys 'C-\\') || tmux select-pane -l"

# splits I can understand (from http://blog.hawkhost.com/2010/06/28/tmux-the-terminal-multiplexer/)
bind | split-window -h
bind - split-window -v

# Support 256 colors (or use tmux -2)
set -g default-terminal "screen-256color"

# resize panes using PREFIX H, J, K, L
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# explicitly disable mouse control
setw -g mouse on

# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on
# set-option -g bell-on-alert on

# Enable Arrows
set-window-option -g xterm-keys on

# installed powerline (fedora)
# source "/usr/share/tmux/powerline.conf"

# local powerline (git submodule)
run-shell "powerline-daemon -q"
source "/home/anass/.powerline/powerline/bindings/tmux/powerline.conf"
```

There's no special tmux powerline configurations.

**Comment by ZyX-I** [comment] 2016-10-22 11:12
Duplicate of #1652

**Closed by ZyX-I** 2016-10-22 11:12 UTC
Labels: c:b:tmux, e:linux, s:duplicate, t:bug
