### ISSUE TITLE
jobnum Segment Shows '0' Regardless of show_zero Setting When Using zpython

### ISSUE THREAD

**Issue by carbonizer** [powerline/powerline#1647] opened 2016-09-16 15:09 UTC
### Issue
If you are using `zpython` in `zsh`, the `jobnum` segment will show `0` when there are zero jobs regardless of the `show_zero` setting.

### Expected Behavior
If there are zero background jobs, and `show_zero` is false, instead of displaying `0`, `powerline` should hide the segment.

### Recreating
This issue can be recreated by including the `jobnum` segment in your shell config and using `zsh` with `zpython` as the `powerline` renderer. I believe that `jobnum` is included in the default shell config, and by default `show_zero` is false.

### Cause
`jobnum()` in `powerline/segments/shell.py` treats `segment_info['args'].jobnum` as type `int` (and that is correct when `zpython` isn't being used). However, the `Args.jobnum` property in `powerline/bindings/zsh/__init__.py ` has a type of `str`. Since `'0' != 0`, the segment is shown.

### Solution
Update the `Args.jobnum` property to convert the type to `int`.

As I identified the cause and solution, I will make the changes and submit a pull request.

**Comment by ZyX-I** [comment] 2016-09-16 20:56
I am unable to reproduce this issue, though I am using libzpython myself. Where did you get zpython from?

**Comment by ZyX-I** [comment] 2016-09-16 20:57
Note that zpython installed by brew is obtained from the repository that does not update.

**Comment by carbonizer** [comment] 2016-09-16 21:01
It is in fact the one installed by brew (00-5.0.5). I will try building zpython from source and see if the issue persists.

**Comment by ZyX-I** [comment] 2016-09-16 21:03
Note that source for zpython is https://bitbucket.org/ZyX_I/zpython. Brew uses https://bitbutket.org/ZyX_I/zsh which was valid until I got reply from zsh-workes that zpython will not be merged into main zsh tree.

**Comment by carbonizer** [comment] 2016-09-17 14:52
It took me a little while, but I got `zpython` building from source. That was not the fix, but upon continuing to dig, I now know my reasoning for the cause was incorrect.

I failed to realize that `zsh.getvalue()` returns an object of the type that matches the type of the `zsh` variable (I previously didn't know that shell variables had types other than string). Now, what seems to be the cause is that `_POWERLINE_JOBNUM`'s declaration in `powerline/bindings/zsh/powerline.zsh` does not include the global flag, so when `_powerline_set_jobnum()` is run later (I believe from a separate python process), `_POWERLINE_JOBNUM` is undefined, and `_POWERLINE_JOBNUM=${(%):-%j}` declares it as a string.

I was able to fix this by changing `integer _POWERLINE_JOBNUM` to `integer -g _POWERLINE_JOBNUM`. Perhaps I needed this because of how I am sourcing `powerline.zsh`; I am sourcing it in an `if` which is in a `for` loop which is in a function I defined in my `.zshrc`.

Is it inappropriate for `_POWERLINE_JOBNUM` to be declared as a global? Am I doing something wrong, or did I discover a weird edge case?

Thank you.

**Comment by ZyX-I** [comment] 2016-09-17 15:14
_powerline_set_jobnum is run by a precmd zsh hook, zsh is *single-threaded* and running anything from “the separate python process” is not possible (unless you want to experience random crashes). If I am not mistaking, missing `-g` from a declaration will yield any problems only if you are sorcing it from a function, otherwise it is implicit and _POWERLINE_JOBNUM should normally be global.

**Comment by carbonizer** [comment] 2016-09-17 15:19
So you agree that the global flag should be added? I would be happy do it; I am still virgin to contributing to open source.

**Comment by carbonizer** [comment] 2016-09-17 16:03
Ah, totally cool. You did a much more thorough job than I would have done.

Sorry to continue my n00bish inquiries, but should I now add your fork as a remote for my fork (which now isn't any different from the original), pull and merge from your fork, test that it works, and close out this issue?

**Comment by ZyX-I** [comment] 2016-09-17 16:32
CI should make it sure that result is not worse. Though I have not added test for sourcing powerline from a function, it can be merged after CI finishes (at the time comment was written this sounds like “right now”).

**Closed** 2016-09-17 16:32 UTC
Labels: c:b:shell, t:bug
