### ISSUE TITLE
fish: normal mode not displayed

### ISSUE THREAD

**Issue by orbisvicis** [powerline/powerline#1292] opened 2015-01-31 23:55 UTC
Nightly powerline, nightly fish. Default configuration.

Insert mode ($fish_bind_mode == "insert")
INSERT > user > ~ > ls -lah

Normal mode ($fish_bind_mode == "default")
user > ~ > ls -lah

**Comment by ZyX-I** [comment] 2015-02-01 08:33
```
$fish_bind_mode == "insert"                                                                                                                                                             master  
Variables may not be used as commands. Instead, define a function like 'function fish_bind_mode; insert $argv; end' or use the eval builtin instead, like 'eval $fish_bind_mode'. See the help section for the function command by typing 'help function'.
```

When I say “exact steps” I mean exact steps. On my system when I have latest master,

```
#fish_vi_mode
set fish_function_path "$HOME/.vam/powerline/powerline/bindings/fish" $fish_function_path
powerline-setup
set fish_key_bindings fish_vi_key_bindings

# vim: ft=fish
```
in configuration and run `~/.local-fish/bin/fish` (fish is compiled with `./configure --prefix=$HOME/.local-fish && make && make install`) I see ` INSERT  zyx  ~/tmp/image/fish-shell ` as expected. When I press escape I see ` DEFAULT  zyx  ~/tmp/image/fish-shell `.

With default configuration (i.e. no Vi key bindings enabled) powerline is not supposed to show anything.

**Comment by ZyX-I** [comment] 2015-02-01 08:53
Actually due to fish-shell/fish-shell#1929 I am seeing the exact opposite: if I remove `set fish_key_bindings fish_vi_key_bindings` and (of course) remove this fucking fishd variable sharing file I am seeing `DEFAULT` in my prompt while I should not. Strange I do not see tests failing, guess this means that fish-shell/fish-shell#1929 is a regression.

**Comment by orbisvicis** [comment] 2015-02-01 16:49
These are my exact steps

```
rm -rf ~/.cache/fish/ ~/.config/fish/ ~/.local/share/fish/ # apparently this is important
set fish_function_path $fish_function_path "/usr/share/powerline/bindings/fish/"
powerline-setup
fish_vi_key_bindings
```

**Comment by ZyX-I** [comment] 2015-02-01 18:44
@orbisvicis You are not supposed to ever run this function directly. Example in docs suggest you use `set -g fish_key_bindings`. Tests test this. Closing as INVALID.

**Closed by ZyX-I** 2015-02-01 18:44 UTC
Labels: bug, invalid, shell

**Comment by ZyX-I** [comment] 2015-02-01 18:46
Example in docs: https://github.com/fish-shell/fish-shell/blob/793784c08778e8b3fb9d8a2a5621bd968db1dfbe/doc_src/bind.txt#L122

Tests: https://github.com/fish-shell/fish-shell/blob/793784c08778e8b3fb9d8a2a5621bd968db1dfbe/tests/bind.expect
