### ISSUE TITLE
Tmux statusline shifting weirdly

### ISSUE THREAD

**Issue by idoqo** [powerline/powerline#1683] opened 2016-11-18 20:15 UTC
Installed powerline on xfce terminal but the statusline has been duplicating and shifting the new one upwards till it fills up the screen and continues scrolling.

**Comment by idoqo** [comment] 2016-11-18 20:22
![Here is what it looks like](http://i.imgur.com/nRmd5JH.png)

**Comment by ZyX-I** [comment] 2016-11-18 21:51
Duplicate of #1652.

**Closed by ZyX-I** 2016-11-18 21:51 UTC
Labels: c:b:tmux, s:duplicate, t:bug
