### ISSUE TITLE
powerline tmux right results in AttributeError: 'list' object has no attribute 'starts with'

### ISSUE THREAD

**Issue by djbender** [powerline/powerline#1359] opened 2015-05-10 18:54 UTC
On master I get the following traceback:

```
$ powerline tmux right -R pane_id=`tmux display -p "#D"`                                                                                             
Traceback (most recent call last):
  File "/usr/local/bin/powerline-render", line 30, in <module>
    write_output(args, powerline, segment_info, get_unicode_writer())
  File "/usr/local/lib/python2.7/site-packages/powerline/commands/main.py", line 156, in write_output
    if args.side.startswith('above'):
AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by ZyX-I** [comment] 2015-05-10 19:19
Duplicate of #1357.

**Closed by ZyX-I** 2015-05-10 19:19 UTC
Labels: c:b:shell, s:duplicate, t:bug

**Comment by djbender** [comment] 2015-05-10 19:29
i'll scope out #1357 and report back over there.
