### ISSUE TITLE
Some segments smother every other segments output

### ISSUE THREAD

**Issue by yggdr** [powerline/powerline#1307] opened 2015-02-09 22:34 UTC
I installed
powerline_status-dev_9823701a55f2828edd8db53d12c46c7b8d578588-py2.7.egg-info
on FreeBSD 10.1, zsh 5.0.7, tmux 1.9a, rxvt-unicode 9.21
via pip and started modifying the config files to play around. I found a few problems with some of the segments:

In tmux, I tried to add the common.sys.cpu_load_percent segment, but it will cause the entire right side to vanish, unless I delete the common.sys.system_load segment. Then it appears like expected.
Same thing with the pairs common.net.external_ip & common.net.hostname, and common.net.network_load & common.wthr.weather.

common.net.internal_ip simply does nothing (no blanking the entire side, but also no output). Setting the interface argument to "re0" didn't change this.

common.net.network_load often shows absurdly high transfer rates. It's basically unusable. Sometimes it errors out with a "Measure interval zero".

common.net.hostname is in the default Shell config, but it doesn't show (it _does_ work in the tmux setting above!).

Now, before I dive into the code, since logging yields nothing except the aforementioned network_load errors, I'd like to see if anyone has an explanation for this strange behaviour.
Thanks.

**Comment by ZyX-I** [comment] 2015-02-10 14:58
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On February 10, 2015 1:34:01 AM EAT, yggdr <notifications@github.com> wrote:
>I installed
>powerline_status-dev_9823701a55f2828edd8db53d12c46c7b8d578588-py2.7.egg-info
>on FreeBSD 10.1, zsh 5.0.7, tmux 1.9a, rxvt-unicode 9.21
>via pip and started modifying the config files to play around. I found
>a few problems with some of the segments:
>
>In tmux, I tried to add the common.sys.cpu_load_percent segment, but it
>will cause the entire right side to vanish, unless I delete the
>common.sys.system_load segment. Then it appears like expected.
>Same thing with the pairs common.net.external_ip & common.net.hostname,
>and common.net.network_load & common.wthr.weather.

Most of the "heavy" segments will not work correctly without a daemon. These are cpu_load_percent, network_load (not that they are too heavy, but they must use rather long interval to measure correctly and this is not possible without daemon), weather and external_ip (network interaction with not too fast servers, mostly applicable to weather segment).

I have no idea why other segments do not work on your system.

>
>common.net.internal_ip simply does nothing (no blanking the entire
>side, but also no output). Setting the interface argument to "re0"
>didn't change this.
>
>common.net.network_load often shows absurdly high transfer rates. It's
>basically unusable. Sometimes it errors out with a "Measure interval
>zero".
>
>common.net.hostname is in the default Shell config, but it doesn't show
>(it _does_ work in the tmux setting above!).

It is not supposed to by default. It only shows when some ssh-specific environment variable is present unless you tell it otherwise.

>
>Now, before I dive into the code, since logging yields nothing except
>the aforementioned network_load errors, I'd like to see if anyone has
>an explanation for this strange behaviour.

I would like to see powerline-lint output. And it is useless to complain without showing your configuration because most segments work for me and they definitely do work in tests.

>Thanks.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/powerline/powerline/issues/1307

-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJNBAEBCgA3BQJU2hxvMBwfMDI7PjIgHTg6PjswOSAQOzU6QTA9NEA+MjhHIDxr
cC1wYXZAeWFuZGV4LnJ1PgAKCRBu+P2/AXZZIuneD/0QtyeSFPveYnZXMaB2zqvo
V5F8iqA5zC63LMGlGwPZXBcKBYEaCNIbA5jiZsfCXUw5dxoj8UNxZ515fpuMHCp3
7lsSBEgtQZsgWlrPnd5RG/HLC952QP0CEAUdWaBScnKle1b3bZT/bmRwJ4j7aByG
LGpKf8YWVHdO4YXS6MEttbib5ag0uQvG8lFe4u0SwvpFg54P6d3cvg9S/4ewNBHw
rnwVwS3E2XgUlXFnZYr+zMDf7M0Vbr0iUWxs+Nmjk6AlL2TNqnw3BuJnfm7lFkAt
fvIfbtQd75723e9ezHZxeaiuuCL4F96m3aFykUTzePfaooFihmBn6/9S+A6Qa1Av
TpslrZeoFAMRNG4jh1TghvidBZxg+GhpTHKcFak+l7HMdCtU0A7D8Bj8VvMZMJTk
CUWudAzSxljW1VGup24vZrsqre8VSMxHiITrCtBIfdYhpDNfRc+3hs2RWCpfbROr
mpHTfN5di9DmDxn41qS1DxbAFJHZ6/rPE9L9+4GNPt7vxZrF9r0nVtpO/uL/5aZt
ZWLz51z/3D3Y46C0vXMH7CC8F8Cyvp6HU+qIbISiThyyHi5otaFovGZIKLbFOnfT
rk3BvL+seoIvilESa4BhCOVE32rytoymNzwMSkyylb+WfQw70VbxqXauXQvcOEcN
GFdrG+EipEnqkAisVeTOyw==
=WQ59
-----END PGP SIGNATURE-----

**Comment by yggdr** [comment] 2015-02-10 19:39
> Most of the "heavy" segments will not work correctly without a daemon. These are cpu_load_percent, network_load (not that they are too heavy, but they must use rather long interval to measure correctly and this is not possible without daemon), weather and external_ip (network interaction with not too fast servers, mostly applicable to weather segment).

Thought so, too, but I started the daemon. At least I thought I did,
because I can't find it via ps aux | grep powerline. But since that also
doesn't work when I have it running in the foreground, I'm going to assume
that's normal behaviour.

> It is not supposed to by default. It only shows when some ssh-specific
> environment variable is present unless you tell it otherwise.

Just realised that I should not use strings when overwriting the boolean "only_if_ssh"...
Side note: why is the same segment, called the same way, once from
shell, once from tmux, working differently? Both setups don't change
"only_if_ssh"'s default value (False), yet once it's active, once it isn't?
(Side side note: what's that lock symbol next to the hostname even ment
to represent?)

> I would like to see powerline-lint output. And it is useless to complain without showing your configuration because most segments work for me and they definitely do work in tests.

This is the error from powerline-lint



Error while checking theme (key /segments/right/list item 1/function)
found highlight groups list (cpu_load_percent_gradient, cpu_load_percent) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/home/yggdrasil/.local/lib/python2.7/site-packages/powerline/config_files/themes/tmux/default.json", line 9, column 48:
     ...  "powerline.segments.common.sys.cpu_load_percent",
                                         ^

Error while checking theme (key /segments/right/list item 1/function)
found highlight group cpu_load_percent_gradient not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 1/function)
found highlight group cpu_load_percent not defined in the following colorschemes: solarized



for the following ~/.local/lib/python2.7/site-packages/powerline/config_files/themes/tmux/default.json



    {
        "segments": {
        	"right": [
        		{
        			"function": "powerline.segments.common.sys.uptime",
        			"priority": 50
        		},
        		{
        			"function": "powerline.segments.common.sys.cpu_load_percent",
        			"priority": 50
        		},
        		{
        			"function": "powerline.segments.common.sys.system_load",
        			"priority": 50
        		},
        		{
        			"function": "powerline.segments.common.time.date"
        		},
        		{
        			"function": "powerline.segments.common.time.date",
        			"name": "time",
        			"args": {
        				"format": "%H:%M:%S",
        				"istime": true
        			}
        		},
        		{
        			"function": "powerline.segments.common.net.hostname"
        		}
        	]
        }
    }
 


While chaning it to



    {
    	"segments": {
    		"right": [
    			{
    				"function": "powerline.segments.common.sys.uptime",
    				"priority": 50
    			},
    			{
    				"function": "powerline.segments.common.net.network_load",
    				"priority": 50
    			},
    			{
    				"function": "powerline.segments.common.sys.cpu_load_percent",
    				"priority": 50
    			},
    			{
    				"function": "powerline.segments.common.sys.system_load",
    				"priority": 50
    			},
    			{
    				"function": "powerline.segments.common.time.date"
    			},
    			{
    				"function": "powerline.segments.common.time.date",
    				"name": "time",
    				"args": {
    					"format": "%H:%M:%S",
    					"istime": true
    				}
    			},
    			{
    				"function": "powerline.segments.common.net.hostname"
    			}
    		]
    	}
    }



now yields this powerline-lint error



Path /usr/home/yggdrasil/.local/lib/python2.7/site-packages/powerline/config_files/themes/tmux/.default.json.swp is not a configuration file

Error while checking theme (key /segments/right/list item 1/function)
found highlight groups list (network_load_sent_gradient, network_load_recv_gradient, network_load_gradient) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/home/yggdrasil/.local/lib/python2.7/site-packages/powerline/config_files/themes/tmux/default.json", line 9, column 48:
     ...  "powerline.segments.common.net.network_load",
                                         ^

Error while checking theme (key /segments/right/list item 1/function)
found highlight group network_load_sent_gradient not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 1/function)
found highlight group network_load_recv_gradient not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 1/function)
found highlight group network_load_gradient not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 1/function)
found highlight groups list (network_load_sent, network_load_recv, network_load) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/home/yggdrasil/.local/lib/python2.7/site-packages/powerline/config_files/themes/tmux/default.json", line 9, column 48:
     ...  "powerline.segments.common.net.network_load",
                                         ^

Error while checking theme (key /segments/right/list item 1/function)
found highlight group network_load_sent not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 1/function)
found highlight group network_load_recv not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 1/function)
found highlight group network_load not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 2/function)
found highlight groups list (cpu_load_percent_gradient, cpu_load_percent) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/usr/home/yggdrasil/.local/lib/python2.7/site-packages/powerline/config_files/themes/tmux/default.json", line 13, column 48:
     ...  "powerline.segments.common.sys.cpu_load_percent",
                                         ^

Error while checking theme (key /segments/right/list item 2/function)
found highlight group cpu_load_percent_gradient not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 2/function)
found highlight group cpu_load_percent not defined in the following colorschemes: solarized


and the aforementioned blanking of the status line.

**Comment by ZyX-I** [comment] 2015-02-10 20:07
> Thought so, too, but I started the daemon. At least I thought I did,
because I can't find it via ps aux | grep powerline. But since that also
doesn't work when I have it running in the foreground, I'm going to assume
that's normal behaviour.

`ps aux | grep powerline` should show you something like `zyx      15127  0.2  0.0 195756 11900 ?        Sl   фев07  14:30 /usr/bin/python2.7 /home/zyx/.local/bin/powerline-daemon` among other processes. It is not a normal behaviour, not unless BSD `ps aux` does something different. I would suggest to check times of run for `powerline shell left` with and without daemon. If daemon works, then they will be very different.

> for the following ~/.local/lib/python2.7/site-packages/powerline/config_files/themes/tmux/default.json

You are not supposed to modify it. All modifications are expected to be in `${XDG_CONFIG_HOME:-$HOME/.config}/powerline`, files from which are merged with `config_files`.

---

Forgot to ask: did you read `internal_ip` and `cpu_load_percent` documentation? They require additional packages to be installed and will not work otherwise. `network_load` also does (I assume that FreeBSD has no /sys/class/net/*/statistics/[rt]x_bytes).

---

> Both setups don't change "only_if_ssh"'s default value (False), yet once it's active, once it isn't?

Tmux environment is taken from the process that first started tmux server and does not change since then unless you push tmux to do so. If you happened to start server from ssh then it will hold `SSH_CLIENT` variable in environment up until you kill the server or remove it with `set-environment`.

And don’t ask me about the lock symbol. I have no idea, most likely it was designed by @Lokaltog (but I am not sure).

**Comment by yggdr** [comment] 2015-02-11 08:44
I thought it strange, too, that I see nothing via ps. But when I run another powerline-daemon in foreground it complains about one already running.
But even when i kill it, I see no difference in the output of `powerline shell left`. Why would there even be any? Shouldn't the daemon only speed it up, but not mess with its contents?

> You are not supposed to modify it.

Yes, I know. But powerline seemed to ignore my stuff in .config, and I was too lazy to try and make it work, because I first wanted to figure out whether this is even the right thing for me.

> did you read internal_ip and cpu_load_percent documentation?

Yes:

    pkg info G "netiface\|psutil"
    psutils-1.17_5                 Utilities for manipulating PostScript documents
    py27-netifaces-0.10.3          Getting network addresses from Python
    py27-psutil-2.1.1              Process utilities module for Python

And no, no /sys/class here

>Tmux environment is taken from the process that first started tmux server and does not change since then unless you push tmux to do so. If you happened to start server from ssh then it will hold SSH_CLIENT variable in environment up until you kill the server or remove it with set-environment.

But I started tmux locally, why would it set `SSH_CLIENT`? It's btw unset in shells within and outside of tmux.

**Comment by ZyX-I** [comment] 2015-02-11 19:27
> But I started tmux locally, why would it set SSH_CLIENT? It's btw unset in shells within and outside of tmux.

It would not. You have not actually checked the configuration and I forgot about this setting: check out `powerline/config_files/themes/shell/__main__.json`.

**Comment by ZyX-I** [comment] 2015-02-11 19:30
> But even when i kill it, I see no difference in the output of powerline shell left. Why would there even be any? Shouldn't the daemon only speed it up, but not mess with its contents?

`powerline shell left` will display tracebacks without daemon (and without setting to redirect log to some file). With all tracebacks are going to daemon log. There are also differences in some segments like network_load/cpu_percent_count that are there simply because powerline does not have enough time.

**Comment by ZyX-I** [comment] 2015-02-11 19:32
And I did not ask for differences in *output*. I asked for differences in *running time*.

**Comment by yggdr** [comment] 2015-02-11 22:38
Today I saw the `__main__`-files, thanks. I also managed to switch to local .config (I simply didn't realise that it's powerline/themes/… instead of powerline/config_files/themes/…), still the same behaviour.

As for the daemon: I'm very confused right now. I can see the daemon with ps/top in the shell window where I started it, but not in other ones?! I'll have to take that to a FreeBSD forum.
Meanwhile, timing the execution shows a definite speedup after the third time of executing the `powerline shell left` command with the daemon running.

If it really where a network lag thing, shouldn't the shell prompt and the tmux statusline have problems  building at the same time when both contain network-related stuff? But the blanking problem seems to only come up when I insert two offending segments in one extension (e.g. tmux), not when adding one each in tmux and shell. That should at least sometimes yield blanking, but it doesn't.

Btw: what are the allowed log_level values? Docs don't mention any and "INFO" didn't seem to log anything in addition to the standard "WARNING".

**Comment by ZyX-I** [comment] 2015-02-12 04:37
With daemon most of heavy segments simply do not show up until they have received data. They are not blanking the entire statusline. And they should not have any problems since heavy segments are threaded and are receiving data “in background”. There is one thread per segment, no separate threads per segment in bindings and all bindings use the same segment instance while using daemon.

Moving configuration to another location should not alter behaviour because all configuration system does with all these directories and different files (like `__main__`) is merging them with each other, only separately per configuration type (config, colors, colorschemes, themes).

Blanking may actually be related to tmux. Can you run `powerline tmux right`, and copy the result to the tmux `status-right` option (`SRIGHT="$(powerline tmux right)" ; echo "$SRIGHT" ; tmux set-option -g status-right "$SRIGHT"`? If it blanks out and `powerline tmux right` returns something not blank, you can report to tmux, giving only the contents of `$SRIGHT` in the report. There was issue somewhere describing this behavior, but it never came to any conclusion because I do not experience it (and for some reason failed to suggest this test).

> Btw: what are the allowed log_level values? Docs don't mention any and "INFO" didn't seem to log anything in addition to the standard "WARNING".

Any integer constant name that is `logging` module attribute name.

**Comment by yggdr** [comment] 2015-02-12 23:28
Alright, with this tmux/default.json


    {
    	"segments": {
    		"right": [
    			{
    				"function": "powerline.segments.common.net.internal_ip",
                    "args":
                    {
                        "interface": "re0"
                    },
    				"priority": 50
    			},
    			{
    				"function": "powerline.segments.common.sys.uptime",
    				"priority": 50
    			},
    			{
    				"function": "powerline.segments.common.sys.cpu_load_percent",
    				"priority": 50
    			},
    			{
    				"function": "powerline.segments.common.sys.system_load",
    				"priority": 50
    			},
    			{
    				"function": "powerline.segments.common.time.date"
    			},
    			{
    				"function": "powerline.segments.common.time.date",
    				"name": "time",
    				"args": {
    					"format": "%H:%M:%S",
    					"istime": true
    				}
    			},
    			{
    				"function": "powerline.segments.common.net.hostname"
    			}
    		]
    	}
    }

I get this `powerline tmux right` output

    #[fg=colour233,bg=default,nobold,noitalics,nounderscore] #[fg=colour247,bg=colour233,nobold,noitalics,nounderscore] 192.168.0.12#[fg=colour241,bg=colour233,nobold,noitalics,nounderscore] #[fg=colour247,bg=colour 233,nobold,noitalics,nounderscore] ⇑  4d 11h 54m#[fg=colour9,bg=colour233,nobold,noitalics,nounderscore] #[fg=colour9,bg=colour233,nobold,noitalics,nounderscore] 53%#[fg=colour241,bg=colour233,nobold,noitalics,nounderscore] #[fg=colour2,bg=colour233,nobold,noitalics,nounderscore] 2.4 #[fg=colour2,bg=colour233,nobold,noitalics,nounderscore]2.7 #[fg=colour2,bg=colour233,nobold,noitalics,nounderscore]2.5#[fg=colour236,bg=colour233,nobold,noitalics,nounderscore] #[fg=colour247,bg=colour236,nobold,noitalics,nounderscore] 2015-02-12#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore] #[fg=colour252,bg=colour236,bold,noitalics,nounderscore] ◷ 23:57:58#[fg=colour252,bg=colour236,nobold,noitalics,nounderscore] #[fg=colour16,bg=colour252,bold,noitalics,nounderscore]  midgard.local % 

Manually setting status-right to this blanks the right side of tmux, no matter how wide the terminal containing tmux is. Taking any one segment out makes it visibil again. Does this value as status-right work for you?

**Comment by ZyX-I** [comment] 2015-02-13 04:35
@yggdr It works fine: I see

![Statusline](https://cloud.githubusercontent.com/assets/322097/6182310/788caa6e-b352-11e4-9908-955fc3fe457c.png)

, but only as long as terminal is wide enough to display it. And I have `status-right-length` set to `150` (your statusline width is 94).

**Comment by yggdr** [comment] 2015-02-13 11:28
Setting status-right-length to 150 doesn't help me. I think I'll try to recreate this behaviour in a VM, if it persists I'll probably contact the maintainer of the FreeBSD tmux port about this since it doesn't seem to be a tmux bug after all.
Unless you have anything else to suggest.

**Closed** 2015-02-20 19:09 UTC
Labels: c:b:shell, c:b:tmux, c:common segments, e:freebsd, s:invalid:foreign bug, t:bug
