### ISSUE TITLE
powerline errors in Neovim, and on uninstalling

### ISSUE THREAD

**Issue by edapess** [powerline/powerline#2213] opened 2022-08-01 19:58 UTC
### This is waht I get when trying to uninstall powerline-status

![image](https://user-images.githubusercontent.com/47182987/182233525-f063c1c6-ede2-4072-ada3-aacc6f5fe94c.png)

### And this is what I get every time by opening Neovim 
![image](https://user-images.githubusercontent.com/47182987/182233806-14447d2b-462d-4be8-826e-9ba505787a6e.png)

### And this for vim
![image](https://user-images.githubusercontent.com/47182987/182239218-ead82cda-5031-4da6-b1c9-5d3007f33ab8.png)

#### _I tried to reinstall powerline-status but as you can see I can't, also first I messed up and installed powerline instead of powerline status, so after that when I realized that something changed(name of package) I uninstalled it and installed powerline-status._

**please help me to figure it out**

**Comment by PH111P** [comment] 2022-08-03 12:41
Hi,

neovim is currently not supported, see https://github.com/powerline/powerline/issues/1287.

Regarding the (un-)installation issue, can you reproduce your issue / does the same issue pop up when uninstalling other packages? To me, it looks like that this might not be related / caused directly by powerline.

**Comment by edapess** [comment] 2022-08-03 13:04
> Hi,
> 
> neovim is currently not supported, see #1287.
> 
> Regarding the (un-)installation issue, can you reproduce your issue / does the same issue pop up when uninstalling other packages? To me, it looks like that this might not be related / caused directly by powerline.

hmmm, yep, there is an error in pip I think, I can't uninstall any of packages via pip

**Comment by PH111P** [comment] 2022-08-03 13:05
Closing this as duplicate / unrelated, then.

**Closed as completed by PH111P** 2022-08-03 13:05 UTC
Labels: s:duplicate, s:invalid:foreign bug
