### ISSUE TITLE
Powerline scrolling new lines instead of updating status bar

### ISSUE THREAD

**Issue by hillna** [powerline/powerline#1658] opened 2016-10-13 15:40 UTC
![2016-10-13-111734_1060x641_scrot](https://cloud.githubusercontent.com/assets/3475233/19355030/d2c1f11a-9136-11e6-8762-3ad66c00e047.png)

Running tmux in termite on Arch. After updating Arch packages, including termite, Powerline creates a new line instead of updating the current status bar.

tmux config:
```
unbind C-b
set -g prefix C-a
bind b send-prefix

# powerline
run-shell "powerline-daemon -q"
source $HOME/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf

# everything gets better with vim bindings
setw -g mode-keys vi

unbind n
unbind p
bind . next-window
bind , previous-window

# copy & paste
unbind [
bind Escape copy-mode
bind p paste-buffer
unbind -t vi-copy 'v'
unbind -t vi-copy 'y'
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-pipe 'xclip -in -selection clipboard'

# we want color ffs
set -g default-terminal "screen-256color"

# we also want mouse
# set -g mouse-utf8 on
set -g mouse on

set -g history-limit 30000

# delay
# set -s escape-time 1

# moving window easy way
bind-key m command-prompt -p "move window to:" "swap-window -t '%%'"

# not-so-easy to type, but easier to remember
unbind %
bind | split-window -h
bind - split-window -v

bind k select-pane -U
bind l select-pane -R
bind j select-pane -D
bind h select-pane -L

# resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
```

zsh config:
```
if [ -e /usr/share/terminfo/x/xterm-256color ]; then
	export TERM='xterm-256color'
else
	export TERM='xterm-color'
fi

ZSH=$HOME/.oh-my-zsh
ZSH_THEME='bira'

DEFAULT_USER='hilln'

setopt AUTO_CD

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
 COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-flow zsh-syntax-highlighting colorize tmux)

# tmux options
ZSH_TMUX_AUTOSTART=false

source $ZSH/oh-my-zsh.sh

. $HOME/.shellrc.load
```

termite config:
```
[options]
font = Monaco 10

# Solarized dark color scheme

[colors]
foreground = #839496
foreground_bold = #eee8d5
#foreground_dim = #888888
background = #002b36
cursor = #93a1a1

# if unset, will reverse foreground and background
highlight = #839496

# colors from color0 to color254 can be set
color0 = #073642
color1 = #dc322f
color2 = #859900
color3 = #b58900
color4 = #268bd2
color5 = #d33682
color6 = #2aa198
color7 = #eee8d5
color8 = #002b36
color9 = #cb4b16
color10 = #586e75
color11 = #657b83
color12 = #839496
color13 = #6c71c4
color14 = #93a1a1
color15 = #fdf6e3

```

**Comment by ZyX-I** [comment] 2016-10-13 15:42
Duplicate of #1652.

**Closed by ZyX-I** 2016-10-13 15:42 UTC
