### ISSUE TITLE
instructions are either incomplete or do not work

### ISSUE THREAD

**Issue by andrewmelnyk** [powerline/powerline#1459] opened 2015-10-01 17:00 UTC
Using mac osx and followed instructions on website.
running this command: pip install --user powerline-status
logs out: Requirement already satisfied (use --upgrade to upgrade): powerline-status in ./Library/Python/2.7/lib/python/site-packages

When I look in the terminal there is no highlighting as shown in the git read me.
The fonts installation instructions are way too vague. What patched font is one supposed to use and even after choosing one in the terminal preferences the color paths do not show up in the terminal.

**Comment by ZyX-I** [comment] 2015-10-01 17:06
There are too many supported systems to provide more concrete steps for installing fonts. I also do not understand what “the color paths do not show up in the terminal” means. Since the issue is about the instructions I am closing it.

**Closed by ZyX-I** 2015-10-01 17:06 UTC
Labels: c:documentation, s:invalid:no information, t:enhancement

**Comment by andrewmelnyk** [comment] 2015-10-01 17:14
Color paths = "Module Dependent Highlighting" does not show up after installing and going through installation process for Max OSX.
<img width="717" alt="screen shot 2015-10-01 at 1 13 52 pm" src="https://cloud.githubusercontent.com/assets/1019709/10227938/4a29cdb8-683e-11e5-9cd8-78a48e797981.png">

**Comment by ZyX-I** [comment] 2015-10-01 17:24
@andrewmelnyk In shell this thing is not configured. It should work if somebody contributes a configuration (e.g. see `colorscheme/vim/default.json`, dictionary `mode_translations`), but by default the only thing for which colors change is the mode segment itself.

**Comment by ZyX-I** [comment] 2015-10-01 17:27
In tmux there are no modes at all. You will such colors only within Vim.

Though I have missed this: what application are you using exactly? I do not see it described and for some reason thought “zsh or fish” (other shells, even have vi-mode, have no means of redrawing prompt (except for one symbol in case of most recent readline) on such event and telling powerline that mode change occurred).
